# Generated by Django 5.1.2 on 2025-05-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='client', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.role'),
        ),
    ]
