# Generated by Django 5.1.2 on 2025-06-03 10:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BelongsTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceOfWealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('belongs_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.belongsto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comm_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('belongs_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.belongsto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comm_phone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('address_nature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.addressnature')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_detail', to=settings.AUTH_USER_MODEL)),
                ('address_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.country')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('primary_holder_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-character IFSC code.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.bankaccounttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('allocation_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.guardian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.relationship')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number (e.g., ABCDE1234F).', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('dob', models.DateField()),
                ('last_4_digis', models.CharField(max_length=4)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('spouse_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('citizenships', models.JSONField(default=list)),
                ('cob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personaldetails_cob', to='users.country')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.gender')),
                ('income_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.incomerange')),
                ('marital_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.maritalstatus')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personaldetails_nationality', to='users.country')),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.occupation')),
                ('pob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personaldetails_pob', to='users.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_personal', to=settings.AUTH_USER_MODEL)),
                ('source_of_wealth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sourceofwealth')),
            ],
        ),
    ]
