# Generated by Django 5.1.2 on 2025-06-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_addressnature_bankaccounttype_belongsto_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationdetails',
            name='personal_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.personaldetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communicationemail',
            name='personal_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.personaldetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communicationphone',
            name='personal_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.personaldetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominee',
            name='personal_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.personaldetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payoutbankaccount',
            name='personal_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.personaldetails'),
            preserve_default=False,
        ),
    ]
