# Generated by Django 5.2 on 2025-06-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_communicationdetails_personal_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communicationemail',
            old_name='address',
            new_name='email',
        ),
    ]
